### ISSUE TITLE
Transparency setting should not affect text!

### ISSUE THREAD

**Issue by ConEmu** [ConEmu/old-issues#1062]
_From [goel.avi...@gmail.com](https://code.google.com/u/102508831919135768415/) on May 10, 2013 07:59:21_

OS version: Win7   SP? x64 ConEmu version: 130227 (x86) _Bug description_ The transparency setting also affects the text on the console. It should either affect only the background or there should be a separate transparency control for text.

_Original issue: http://code.google.com/p/conemu-maximus5/issues/detail?id=1063_

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on May 10, 2013 09:33:49_

**Status:** Duplicate  
**Mergedinto:** 750

**Comment by Nevitones** [comment]
Hi, there is any way to have only the background transparency?

**Comment by Maximus5** [comment]
No. It's in roadmap.

**Comment by davidporter** [comment]
Almost a year to the day, what's the status on this, I just downloaded and am having this issue today. ???

**Comment by Maximus5** [comment]
This is deprecated issue tracker.
I have many other things to implement and fix.
