### ISSUE TITLE
Switching virtual desktops triggers tray popup "ConEmu was hidden from some program"

### ISSUE THREAD

**Issue by ConEmu** [ConEmu/old-issues#656]
_From [Juha.Ha...@gmail.com](https://code.google.com/u/110619682991855198638/) on July 27, 2012 09:25:01_

OS version: Win7 x64 ConEmu version: 120727 x64
Far version (if you are using Far Manager): Not in use

When combining ConEmu with a virtual desktop manager (Dexpot in this case) switching to second desktop triggers a tray popup message " ConEmu was hidden by some program". This is undesirable as the "hiding" was done intentionally and the user doesn't need to be warned about it. Problem is made worse by having several open sessions on the second desktop, causing as many alert popups to be displayed in sequence on the tray area. ... _Steps to reproduction_ 1. Start ConEmu in virtual desktop `#1`
2. Switch to virtual desktop `#2`
3. Observe popup in tray area, multiplied with how many ConEmu windows are open at the time, displayed sequentially

_Original issue: http://code.google.com/p/conemu-maximus5/issues/detail?id=656_

**Comment by ConEmu** [comment]
_From [jmugur...@gmail.com](https://code.google.com/u/103466037919225061032/) on July 29, 2012 15:14:13_

I had this issue too, and the only thing I found about it was a Issue in russian that is not very detailed, but was enough to show me the way to solve this, set DownShowHiddenMessage to 01 and you are good to go (I did this in the xml, as I use the portable mode, but you can do the same in the registry I guess)

regards

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on July 29, 2012 16:54:23_

Yeah, you are right. Already forgot about this option. Thought, need to be presented on Features page. And may be I'll check again this issue, may be there is a way to determine desktop manager (previous try failed).

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on August 09, 2012 03:18:38_

Interesting, that virtuawin.sourceforge.net does not interfere with conemu... working without popups ;)

**Comment by ConEmu** [comment]
_From [jmugur...@gmail.com](https://code.google.com/u/103466037919225061032/) on August 10, 2012 05:43:43_

I used virtuawin some time ago, but have been running mdesktop for a couple of years now, much better than any other I tried before. Worth checking out.

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on October 24, 2013 00:45:17_

There is an option "DownShowHiddenMessage", you may change it manually in the registry of xml.

**Status:** Fixed

**Comment by haveamission** [comment]
Which XML file precisely?

**Comment by erms77** [comment]
Which XML file precisely?

**Comment by erms77** [comment]
File :  **ConEmu.xml**
In directory : **%ConEmuDir%\**

Doc : https://conemu.github.io/en/ConEmuXml.html#search-sequence

**Comment by fms615** [comment]
Was getting this annoying popup using cmder.

There are multiple ConEmu.xml files or variants of in the cmder directory. So it wasn't clear which file needed to have the DownShowHiddenMessage property updated to "01" as mentioned by others.

opening up settings shows the path:
(your install location)\Cmder\vendor\conemu-maximus5\ConEmu.xml

Or you can do it from

Settings > General > Confirm > uncheck => "Show ' . . . was hidden' warning in TSA"

![image](https://user-images.githubusercontent.com/17858120/51298841-14435500-19db-11e9-99a9-5e92bb8c2ffc.png)
