### ISSUE TITLE
Full support of fallback font if main font not contains a glyph (aka UNICODE range)

### ISSUE THREAD

**Issue by ConEmu** [ConEmu/old-issues#896]
_From [nanofo...@gmail.com](https://code.google.com/u/117990161848247711282/) on January 21, 2013 04:24:56_
1. Select font 'Lucida Callygraphy'
2. Take a look at attached text file in FAR: Japanese glyphs are OK
3. Russian text: unsupported

As I see, ConEmu easily handles Japanese glyphs even if main font does not contains those. If it is not a big problem then could You support this font fallback mechanism on other character ranges not supported in the main font? There is a Windows function 'GetFontUnicodeRanges'.

Another much simpler but perfect solution would be an adjustable UNICODE threshold value for fallback: for example I set it to U+0100 and all non-western-Latin characters will came from Lucida.

I would like to use a font which contains Latin characters only but I having non-Latin files too which names are unreadable now.

(I attached Lucida Calligraphy however it is shipped with Windows)

**Attachment:** [JAP_RUS_UTF8.txt](http://code.google.com/p/conemu-maximus5/issues/detail?id=896)

_Original issue: http://code.google.com/p/conemu-maximus5/issues/detail?id=896_

**Comment by ConEmu** [comment]
_From [nanofo...@gmail.com](https://code.google.com/u/117990161848247711282/) on January 21, 2013 04:26:27_

Ahh - I forgot that font :)

**Attachment:** [LCALLIG.TTF](http://code.google.com/p/conemu-maximus5/issues/detail?id=896#hc1)

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on January 21, 2013 05:18:18_

ConEmu already provides "fallback". It may use alternative font (specified in "Change frames font") for specified char-range (search "Settings- ConEmu .reg" for "fFixFaRBordersRanges").

**Status:** New

**Comment by ConEmu** [comment]
_From [nanofo...@gmail.com](https://code.google.com/u/117990161848247711282/) on January 21, 2013 06:34:38_

FixFarBordersRanges works well, thank You! Using ranges is very wise feature, congratulations!

Any chance for (even an internal) setting to use anti-aliasing on these characters?

----------------

A made a TrueType font for myself and spent _a_lot_ of time to trying insert non-Latin glyphs into it without success (that not as easy because of metrics). With FixFarBordersRanges now I'm very happy, thank You again!

**Comment by mnpenner** [comment]
Where is this "Settings-ConEmu.reg"? How do I search it? I want to enable this FixFarBordersRanges setting because right now that Alternative font option seems to be doing nothing.

**Comment by Maximus5** [comment]
Why do you ask here in the deprecated issues instead of looking at the settings dialog?
http://conemu.github.io/en/SettingsMain.html

**Comment by mnpenner** [comment]
@Maximus5 Because the settings dialog is pointing me towards `FixFarBordersRanges` and this is the only thing that turned up on Google when searching for it.

![image](https://cloud.githubusercontent.com/assets/1112998/22629449/3dad456a-eb9b-11e6-958a-7ff4bd60db06.png)

I wanted to "fallback" to [FontAwesome](http://fontawesome.io/cheatsheet/) for all chars in the range F000-FFFF but the "Unicode ranges" setting doesn't seem to enforce that.

**Comment by Maximus5** [comment]
https://github.com/Maximus5/ConEmu/issues/988

**Comment by mnpenner** [comment]
That looks exactly like the issue I've been experiencing. Thank for pointing me in the right direction.

If that tooltip is no longer relevant, it should probably be updated too 😃
