### ISSUE TITLE
Ctrl+Tab and Ctrl+Shift+Tab both switch in backwards order

### ISSUE THREAD

**Issue by ConEmu** [ConEmu/old-issues#901]
_From [robertco...@yahoo.com](https://code.google.com/u/106635827517471658382/) on January 21, 2013 11:56:19_

OS version: WinXP SP3 x86 ConEmu version: ConEmu .Maximus5.130120

_Settings_
Settings>Features>Tabs> "Internal Ctrl+Tab" set to On
Settings>Features>Tabs> "Lazy tab switch" set to Off
Settings>Features>Tabs> "Recent mode" set to Off
Settings>Keys & Macro> "Next tab" set to Ctrl+Tab
Settings>Keys & Macro> "Previous tab" set to Ctrl+Shift+Tab _Steps to reproduction_ 1. Right click taskbar entry > Active Console > Duplicate root
2. Right click taskbar entry > Active Console > Duplicate root
3. Now there should be 3 tabs open
4. Try Ctrl+Tab and Ctrl+Shift+Tab - both result in same tab switch behavior.

_Current Buggy Behavior_
Ctrl+Tab goes from Tab1-->Tab3-->Tab2-->Tab1
Ctrl+Shift+Tab goes from Tab1-->Tab3-->Tab2-->Tab1

_Desired behavior_
Ctrl+Tab goes from Tab1-->Tab2-->Tab3-->Tab1
Ctrl+Shift+Tab goes from Tab1-->Tab3-->Tab2-->Tab1

_Original issue: http://code.google.com/p/conemu-maximus5/issues/detail?id=901_

**Comment by ConEmu** [comment]
_From [robertco...@yahoo.com](https://code.google.com/u/106635827517471658382/) on January 22, 2013 00:17:33_

This can be closed. I fixed it via removing the key bindings for Ctrl+Tab and Ctrl+Shift+Tab. It seems that Ctrl+Tab and Ctrl+Shift+Tab hotkeys are implemented natively by the window manager and should not be redefined in "Keys & Macros".

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on January 22, 2013 00:37:09_

What have you defined in "Macro" and why you have decided to do so?

I want to know, for avoiding possible vagueness.

**Comment by ConEmu** [comment]
_From [robertco...@yahoo.com](https://code.google.com/u/106635827517471658382/) on January 22, 2013 05:13:47_

The problem was being caused because Ctrl+Tab was set for "Switch next console".

These three being set at the same time caused the problem:
User - Ctrl+Tab - Switch next console
System - Ctrl+Tab - Next tab (may be disabled)
System - Ctrl+Shift+Tab - Previous tab (may be disabled)

Perhaps 'Switch next console' / 'Next tab' and 'Switch previous console' / 'Previous tab' can be merged if they serve the same function.

**Comment by xcjs** [comment]
Apologies if this isn't the right place for this, but is there a way to make Ctrl + Tab and Ctrl + Shift + Tab behave the same as Ctrl + Tab + Left and Ctrl + Tab + Right? 

I'm having the same issue as @robertco...@yahoo.com

**Comment by Maximus5** [comment]
@xcjs Just disable "Recent mode"

**Comment by xcjs** [comment]
@Maximus5 Thanks! Sorry, that seems obvious now!

**Comment by vvscher** [comment]
> @xcjs Just disable "Recent mode"

you saved me!
Thanks!

**Comment by tgeng** [comment]
Is there a way to allow custom bindings to these commands? For example, I have been used to `Alt+U` to switch to the next tab? Thank you!

**Comment by Maximus5** [comment]
Every combination could be configured.
https://conemu.github.io/en/SettingsHotkeys.html
