### ISSUE TITLE
Beeps on tab-autosuggestions when using SSH

### ISSUE THREAD

**Issue by ConEmu** [ConEmu/old-issues#988]
_From [antito...@gmail.com](https://code.google.com/u/100826737282304734103/) on March 17, 2013 05:01:28_

OS version: Win8 x64 Clean install ConEmu version: 130223 [64] Far version (if you are using Far Manager): ? _Bug description_ ConEmu cries out some sort of sound on every time I'm ssh-ed to my local virtual machine and I'm doing tab autosuggestions.
It beeps. Also the beep is somehow distored, a lot of noise.

Relates to: http://superuser.com/questions/544036/conemu-disable-bell _Steps to reproduction_ 1. Have a MinGW console open
2. SSH to something
3. Try tabbing (tab autosuggestions)

_Original issue: http://code.google.com/p/conemu-maximus5/issues/detail?id=988_

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on March 17, 2013 05:10:16_

This is NOT a ConEmu bug. ConEmu does not produce any sounds.
Beeps are produced by your ssh client.

There was suggestion already, about allowing to configure or disable beeps on printing char(7) to the console.
May be it will be implemented in future.

**Labels:** -Type-Defect Type-Other

**Comment by ConEmu** [comment]
_From [antito...@gmail.com](https://code.google.com/u/100826737282304734103/) on March 17, 2013 06:18:28_

Can you point to the suggestion that was done? I want to vote for it and i can't find it.

The beeps is from the SSH client as you said. I'm using Git for windows which uses msys. And msys will read the logged in user config for "bell-style" from inputrc. 

Disabling the bell in inputrc is not a solution as when I login with SSH to another PC the bell there is most probably enabled.

**Comment by ConEmu** [comment]
_From [ConEmu.M...@gmail.com](https://code.google.com/u/116287257743594353797/) on March 17, 2013 06:26:11_

Can't find the issue now. May be suggestion was from mailing list or superuser.

**Comment by ConEmu** [comment]
_From [ohone...@gmail.com](https://code.google.com/u/106250740934110470126/) on May 30, 2013 08:16:02_

I disable all the window sound.
Control Panel\Hardware and Sound\Change system sounds\No sounds (sound scheme)

:)

**Comment by ConEmu** [comment]
_From [ram.rac...@gmail.com](https://code.google.com/u/103064103717807496468/) on June 18, 2013 06:16:21_

I'm getting this beep while I'm not using SSH at all. I get it when using `less` and trying to scroll up when I'm at the top. This is quite annoying.

**Comment by ConEmu** [comment]
_From [sruok...@gmail.com](https://code.google.com/u/108442808192740087395/) on October 30, 2013 02:35:48_

This is not a bug, but it would be nice to have an option in settings for disabling the bell sound.

**Comment by ConEmu** [comment]
_From [w...@wykeham.net](https://code.google.com/u/118097519615478631055/) on February 28, 2014 07:07:41_

Yes, this is a problem for me too. Have been able to disable the bell in other applications.

I'm not sure what is actually generating the tone - is it being passed up to windows or being caught by ConEmu ? Whatever is doing it, on my machine the sound clip appears to be truncated - it's not playing the whole thing.

That's why it sounds distorted, because cutting off the waveform produces a square wave.

**Comment by eversor1** [comment]
This is still an extremely annoying problem, and I disagree that it is a terminal, shell, or SSH issue. If I open Cygwin bash, I can do all of the above using tab-completion and not hear a single sound. However, if I do the same in ConEmu it starts screaming bells like a bludgeoned child. Please fix this bug.

**Comment by Maximus5** [comment]
1. This site is read-only.
2. ConEmu is a terminal. You say: "I disagree that it is a terminal issue". Conclusion: This is not a ConEmu issue.
3. Option to suppress beeps **produced by your console applications** was implemented long ago!
- https://conemu.github.io/en/SettingsFeatures.html
- https://conemu.github.io/en/Delusions.html
- https://conemu.github.io/en/CygwinMsys.html
- https://conemu.github.io/en/TerminalVsShell.html
- https://conemu.github.io/en/ConsoleApplication.html
- https://conemu.github.io/en/BadIssue.html#Update_your_installation

**Comment by eversor1** [comment]
My apologies. You are quite right, this feature is now available. Updates were not taking place, and this feature is available in the latest unstable alpha version. Console applications are incapable of producing beeps or any sound (with the exception of specific apps that correctly address the OS and underlying hardware to do so). It is up to the terminal emulator to interpret these codes however it sees fit. We are saying the same thing, I just said it poorly previously. Thank you for adding this feature!
